### PR TITLE
Date histogram

### PR DESCRIPTION
**Pull request by st0012**
@ankane I added data_histogram to aggregations, here's the [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html).
And this is related to #516

### CODE REVIEW

**Comment by ankane** [comment]
Hey @st0012, thanks! 2 things:

1. It looks like the tests are failing
2. Please don't add to the Gemfile unless necessary for a feature

**Comment by st0012** [comment]
@ankane 
1. It looks like the `date_histogram` has different behavior in different versions of elasticsearch, so my test passed in some versions and failed in others. Do you have any advice for this kind of situation?
2. Sorry that I forgot to delete that from Gemfile.

**Comment by ankane** [comment]
The test helper has [methods to help with this](https://github.com/ankane/searchkick/blob/master/test/test_helper.rb#L28).

**Comment by st0012** [comment]
@ankane got it, thanks!

**Comment by st0012** [comment]
Tests fixed 😁

**Comment by ankane** [comment]
Awesome, looking good. Last step: add it to the readme with the tag [master], like [here](https://github.com/ankane/searchkick#multiple-indices).

**Comment by st0012** [comment]
@ankane done

**Comment by ankane** [comment]
Awesome, thanks @st0012 👍

**Pull request merged**
