### PR TITLE
Feature/add scoping to results

### PR DESCRIPTION
**Pull request by cdimartino**
Adding ability to push AR :includes and :scopes down the finder in the searchkick query results.

### CODE REVIEW

**Comment by trostli** [comment]
Any chance this PR could be brought back to life @cdimartino ? would love to see scoped results in searchkick

**Comment by cdimartino** [comment]
Hey folks - sorry this has taken so long.  Attempting to get a good rebase, failing miserably...  will see if I can resurrect this.

**Comment by waleedasif322** [comment]
Would be great to see this. I'll see if I can submit a PR that works

**Comment by ankane** [comment]
Cleaning up PRs. Still not sure I understand the use case, but feel free to create a new PR with an explanation. Thanks again @cdimartino 👍

**Pull request closed without merging**
