### PR TITLE
[1353] Refresh mode option

### PR DESCRIPTION
**Pull request by TikiTDO**
Example of potential solution to #1353

### CODE REVIEW

**Comment by TikiTDO** [comment]
Here's what I was thinking for this feature. Let me know if you have a better idea of where to put the param for this mode.

**Comment by TikiTDO** [comment]
Could even make it more generic, like `bulk_import_options` or even just `import_options` that you could merge into the request.

**Comment by ankane** [comment]
Hey @TikiTDO, thanks for this PR as well! Based on the discussion in #1353, my initial thoughts are this should be a new reindex `mode` rather than a global option.

**Comment by TikiTDO** [comment]
Unfortunately I've now moved on to other parts of our system after we monkey-patched this functionality in an initializer. Since then, I haven't worked with this library in over a month which means it's all but faded from memory at this point.

I can revisit this if I return back to indexing at some point, but my current focus is an entirely different system in a different language, so  I'm not sure when I fill have the time to figure out how and where to hook into the index mode, and also write some good tests for that.

**Comment by ankane** [comment]
No worries, I appreciate you taking a shot at it

**Pull request closed without merging**
