### PR TITLE
Use Module#prepend instead of deprecated alias_method_chain 

### PR DESCRIPTION
**Pull request by ovelar**

### CODE REVIEW

**Comment by ankane** [comment]
Awesome, thanks Lars! :+1:

**Comment by nandokakimoto** [comment]
Hi, @ankane . We are still using version 0.9.1. Can you help us move this commit to older versions of the gem? Thanks.

**Comment by ankane** [comment]
Hey @nandokakimoto, you should be able to fork the gem and apply the change above.

**Comment by nandokakimoto** [comment]
Hi @ankane, thanks for your response. I already have the changes [here](https://github.com/nandokakimoto/searchkick/compare/nandokakimoto:v0.9.1-tag...fix-deprecation-warning-rails-5). I was wondering if it makes sense to apply them in this repo as well (v0.9.2). Otherwise, I will go with the forked repo as you suggested. Thanks.

**Comment by ankane** [comment]
No plans to maintain past versions, with the exception of critical security patches.

**Pull request merged**
