### PR TITLE
Added support for multi_match query with cross_fields type

### PR DESCRIPTION
**Pull request by technopreneurG**
Added support for multi_match query with cross_fields type.
example usage
`
Product.search "abc def ghi", fields: ['field1^20', 'field2^10'], cross_fields: true
`

### CODE REVIEW

**Comment by ankane** [comment]
Hey @technopreneurG, thanks for the PR 👍  I have a good amount of feedback on the implementation, but I'm currently torn on the value of the feature after finding out about the `misspellings` limitation. My recommendation would be for devs to index search data into a single field if they want to search across fields.

**Comment by jprosevear** [comment]
Indexing into a single field prevents per field boosting:
https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_queries.html#_per_field_boosting

What is the misspellings limitation in this case?

@ankane do you have any specific architecture in mind for implementing this?

**Comment by technopreneurG** [comment]
Hi @ankane , 

As mentioned in #727 
Quoting from https://www.elastic.co/guide/en/elasticsearch/guide/2.x/fuzzy-match-query.html  
>Tip
>Fuzziness works only with the basic match and multi_match queries. It doesn’t work with phrase matching, common terms, or cross_fields matches.

This PR should help with these use-cases:
1) Entity Search (as described in https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_entity_search.html)
2) Per field boosting (as described in  https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_queries.html#_per_field_boosting)

Do let me know if there are any changes in the implementation you would like to see.

For handling misspellings, I would assume spellings would have been already auto-corrected by using  https://github.com/ankane/searchkick#suggestions so that entities are correctly identified from the search query. Do let me know your suggestions. I can work on another PR for misspellings.

**Comment by technopreneurG** [comment]
Hi @ankane,  Do you have any suggestions/or a different approach for the same?

**Comment by ankane** [comment]
Hey @technopreneurG, thanks again for the PR. I don't see a big benefit for adding cross_fields right now. For the two use cases above, I recommend writing a custom query.

**Comment by philipgiuliani** [comment]
@ankane Can you provide an example for a multi_match custom query with searchkick? Or should I just use the JSON api?

**Comment by lucasmpereira** [comment]
@ankane I too, will be very grateful if you can provide an example of custom query to suport crossfield search?

**Comment by marwenB** [comment]
@ankane we will be very grateful if you can provide an example of custom query to suport crossfield search.
Thank you

**Comment by ankane** [comment]
Check out the [Advanced Search](https://github.com/ankane/searchkick#advanced-search) section for how to use custom queries. I don't have an example for cross fields, so please check out the Elasticsearch docs and share.

**Pull request closed without merging**
