### PR TITLE
Use bool filters instead of and/or filters except for geo-spacial, an…

### PR DESCRIPTION
**Pull request by elguapo1611**
…d range filters

### CODE REVIEW

**Comment by elguapo1611** [comment]
Follows some of the advice from this blog post: https://www.elastic.co/blog/all-about-elasticsearch-filter-bitsets

**Comment by meetrajesh** [comment]
Have we done any tests to prove that this is actually faster for the more recent versions? The blog post linked indicates the advice provided is now deprecated.

**Comment by elguapo1611** [comment]
@meetrajesh this feature is apparently fixed in es 2.0.  And/Or filters will use bitsets, but for everyone still using 1.7, this will perform better.

**Comment by ankane** [comment]
Added the additional test case and ensured there are no more `and` filters. Sorry we couldn't get this in sooner.

**Pull request closed without merging**
