### PR TITLE
custom search analyzer

### PR DESCRIPTION
**Pull request by hooopo**
related issue: https://github.com/ankane/searchkick/issues/333

with this PR, we can do this:

```ruby
Searchkick.searchkick_search_analyzer = :ik_max_word
Searchkick.searchkick_search2_analyzer = :ik_smart
```

and perform query:

```text
curl http://localhost:9200/hub_product/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"滴滴打车","boost":10,"operator":"and","analyzer":"ik_max_word"}}},{"match":{"_all":{"query":"滴滴打车","boost":10,"operator":"and","analyzer":"ik_smart"}}},{"match":{"_all":{"query":"滴滴打车","boost":1,"operator":"and","analyzer":"ik_max_word","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"滴滴打车","boost":1,"operator":"and","analyzer":"ik_smart","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":1000,"from":0,"timeout":"101s","_source":false}'
```

### CODE REVIEW

**Comment by ankane** [comment]
Hey @hooopo, thanks for the PR 👍  I'm not sure it makes sense for Searchkick to provide this specific customization, but maybe other options can be added to suit your needs. Can you explain more about what the analyzers do?

**Comment by hooopo** [comment]
searchkick_search2
```ruby
Product.searchkick_index.tokens("中华人民共和国国歌", :analyzer => "searchkick_search2")
=> ["中", "华", "人", "民", "共", "和", "国", "国", "歌"]
```

searchkick_search
```ruby
Product.searchkick_index.tokens("中华人民共和国国歌", :analyzer => "searchkick_search")
=> ["中华", "华人", "人民", "民共", "共和", "和国", "国国", "国歌"]
```

ik_max_word
```ruby
Product.searchkick_index.tokens("中华人民共和国国歌", :analyzer => "ik_max_word")
=> ["中华人民共和国", "中华人民", "中华", "华人", "人民共和国", "人民", "共和国", "共和", "国", "国歌"]
```

ik_smart
```ruby
Product.searchkick_index.tokens("中华人民共和国国歌", :analyzer => "ik_smart")
=> ["中华人民共和国", "国歌"]
```

with chinese,we want to use `ik_smart` as analyzer for indexing:

```
            company_name: {
              type: 'string',
              analyzer: 'ik_smart',
              boost: 7,
            }
```

so, when searching, we also want to use ik related analyzer.

**Comment by ankane** [comment]
Hey @hooopo, sorry for the delay. I'd love to support Chinese out of the box with Searchkick, but my knowledge on how to do that is pretty limited. It'd be great to have a single option that took care of everything.

It sounds like you're using [this plugin](https://github.com/medcl/elasticsearch-analysis-ik), and you want to make the following changes:

- index analyzer = `ik_smart`
- search analyzers = `ik_smart` and `ik_max_word`

Is that right?

**Comment by hooopo** [comment]
@ankane Yes, I use https://github.com/medcl/elasticsearch-analysis-ik , and want to index using `ik_smart`, to search using `ik_smart` and `ik_max_word`. I want to replace searchkick_search2_analyzer and searchkick_search_analyzer optional.

**Comment by ankane** [comment]
Hey @hooopo, how are you setting the index analyzer to `ik_smart`? (it'd be nice to have an easy way to do that as well)

What do you think of?

```ruby
Searchkick.index_analyzer = "ik_smart"
Searchkick.search_analyzers = ["ik_smart", "ik_max_word"]
```

**Comment by ankane** [comment]
Hey @hooopo, I added the ability to do `language: "chinese"` to the `searchkick3` branch. Please try it out and let me know what you think.

**Comment by ankane** [comment]
cc @imWildCat and @fanix since you both thumbs up'd a comment

**Comment by hooopo** [comment]
LGTM, thanks you very much.

**Pull request closed without merging**
