### PR TITLE
Custom search analyzer

### PR DESCRIPTION
**Pull request by kahirul**
Add feature to customize analyzer upon searching. @ankane 

Might solve #333.

Let say you have custom analyzer named `super_thai`.  To use `super_thai` analyzer:

```ruby
Product.search "แอปเปิ้ลกาล่า แจ๊ส", fields: [ { name: :super_thai_custom_analyzer } ]
```

### CODE REVIEW

**Comment by edwinlunando** [comment]
@ankane I need this. Can you merge this PR?

**Comment by kahirul** [comment]
Closing this PR, favouring custom mapping with `nested type` when indexing and `multi match` during searching.

**Comment by hooopo** [comment]
@kahirul can you explain 

> favouring custom mapping with object type when indexing and multi match during searching

in detail?

**Comment by kahirul** [comment]
Here are how my mapping roughly look like

```json
{
   "products": {
      "mappings": {
         "_default_": {
            // ... default mapping
         },
         "product": {
            "index_analyzer": "default_index",
            "dynamic_templates": [
               // ... dynamic templates
            ],
            "properties": {
               "name": {
                  "properties": {
                     "en": {
                        "type": "string",
                        "index": "not_analyzed",
                        "fields": {
                           "analyzed": {
                              "type": "string",
                              "analyzer": "english"
                           }
                        }
                     },
                     "id": {
                        "type": "string",
                        "index": "not_analyzed",
                        "fields": {
                           "analyzed": {
                              "type": "string",
                              "analyzer": "SUPER_AWESOME_ID_ANALYZER"
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```


And this is how I search (notice *multi_match*)

```json
POST products/_search
{
    "query": {
        "multi_match": {
           "query": "Apple",
           "fields": [
               "name.en.analyzed",
               "name.id.analyzed"
            ]
        }
    }
}
```

**Comment by hooopo** [comment]
@kahirul thanks! looks pretty cool 👍

**Comment by gsdean** [comment]
It would be nice to be able to use `merge_mappings` with a custom analyzer and not have to replace the entire search body. 

Seems like providing the analyzer at query time is a good compromise, no?

**Pull request closed without merging**
