### PR TITLE
Add support for cross-fields - fixes #707

### LINKED ISSUE #707: New feature: Cross fields search
https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_queries.html

### PR DESCRIPTION
**Pull request by sgerov**

### CODE REVIEW

**Comment by ankane** [comment]
Thanks for another PR @savayg! 👍 

It'd be great to make this work with misspellings.

I was also hoping it could be added as a boolean option over a new match type if possible so it could work with the other match types like `word_start`.

```ruby
Product.search "pink app", fields: [:name, :color], match: :word_start, cross_fields: true
```

And make `cross_fields: true` the default in Searchkick 2.0.

**Comment by oyeanuj** [comment]
@savayg Curious, if this is still on your radar? Would love `cross_fields` support!

**Comment by savayg** [comment]
@ankane fuzziness doesn't seem to work with cross_fields (https://www.elastic.co/guide/en/elasticsearch/guide/2.x/fuzzy-match-query.html in the bottom), does that take misspellings away or you have in mind something else?

@oyeanuj I have been quite busy but will try to finish what I started in the following weeks

**Comment by ankane** [comment]
@savayg Looks like it takes away misspellings.

**Comment by technopreneurG** [comment]
Hi @savayg, @ankane,

I had a need to do cross_fields query and since this PR is long pending, I have taken a shot at it with inputs from your PR & comments and submitted mine for review #871.

Hope it is useful.

**Comment by hamdibayhan** [comment]
@ankane Do you think merge this PR?

**Comment by ankane** [comment]
I don't see a strong reason to add `cross_fields` to Searchkick syntax right now (you can always write a custom query for it), so going to close. Big thanks for the PR @sgerov 👍  Sorry this took so long to resolve.

**Pull request closed without merging**
