### PR TITLE
README Update - Clarify how to work with multi_search

### PR DESCRIPTION
**Pull request by ramonpm**
Hey there, I recently had to refactor an application to use `multi_search` for better performance and noted the documentation wasn't very good at that point. I wish I had this info right away here, which would have saved me a couple of hours digging into this.

I initially created a Stackoverflow question about it https://stackoverflow.com/questions/69137572/how-to-use-searchkick-multi-search-along-with-with-highlights-undefined-met but after no response dug into the codebase and discovered the important parts.

So, here's my contribution to the documentation, let me know if anything seems off or what should be written differently.

Btw, Searchkick is awesome ;). Thank you.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @ramonpm, thanks for the PR! It looks like some delegation methods like `with_highlights` were missing, and should be fixed in the commit above. Users shouldn't need to call `execute` directly.

**Comment by ankane** [comment]
Also added a test case to catch this in the future.

**Comment by ramonpm** [comment]
hey @ankane, what's the exact way to use multi_search + with_highlights then?

`search_query.with_highlights`? instead of `search_query.execute.with_highlights`? If that's the case I already have the PR updated.

**Comment by ankane** [comment]
Yeah, that's the recommended way. The readme currently has "Then use `products` and `coupons` as typical results.", which should now work with all methods, so I don't think an update is needed.

**Comment by ramonpm** [comment]
ok, your call, closing the PR then. Thanks.

**Pull request closed without merging**
