### PR TITLE
Function score queries also set boost_mode

### PR DESCRIPTION
**Pull request by itay-grudev**

### CODE REVIEW

**Comment by itay-grudev** [comment]
@ankane I'm not sure exactly whats causing the mongoid 6 issue for the failing spec. Think you can help?

**Comment by ankane** [comment]
Hey @itay-grudev, thanks for another PR 👍  Can you explain this more?

**Comment by itay-grudev** [comment]
@ankane I was referring to the failing specs on Travis.

**Comment by ankane** [comment]
@itay-grudev I was referring to the PR w/ no description :) A test case would be great as well.

**Comment by itay-grudev** [comment]
I took a quick look at your test suite and I'm not sure exactly how it works. It'll need more reverse-engineering. And I won't have time to mess around with it for now. I can get back to that later when I have time.

**Comment by ankane** [comment]
Instructions are here: https://github.com/ankane/searchkick#contributing

**Comment by itay-grudev** [comment]
@ankane I meant writing tests not running them. I did run your specs locally and they passed fine.

**Comment by ankane** [comment]
Hey @itay-grudev, thanks again for the PR. Unfortunately, going to close since I'm still not sure what the purpose is. Feel free to create a new PR with a description and ideally a test case.

**Pull request closed without merging**
