### PR TITLE
Add `histogram` aggregation

### PR DESCRIPTION
**Pull request by divineforest**
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html

### CODE REVIEW

**Comment by ankane** [comment]
Hey @divineforest, thanks for the PR, including tests 💯  Since Elasticsearch has a lot of different aggregation types, I'd prefer not to add them one by one, but instead have developers use `body_options`.

```ruby
Product.search "pear", body_options: {aggs: {prices: {histogram: {field: :price, interval: 10}}}
```

I'll update the readme to make this more clear.

**Comment by divineforest** [comment]
@ankane but since `date_histogram` is already there a regular `histogram` seems like it is missing :(

**Comment by ankane** [comment]
@divineforest Other aggregation types were added before this decision was made. Have to start somewhere.

**Comment by divineforest** [comment]
@ankane ok, thanks for the explanation :)

**Pull request closed without merging**
