### PR TITLE
Use an after create hook instead of manual reindex

### PR DESCRIPTION
**Pull request by tilsammans**
I always use FactoryGirl's `after create` hook to reindex. Since typically I only create only a handful models needed for each test, this is very quick and I don't have to remember anything.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @tilsammans, thanks for the PR 👍 

Is there a good way to do this conditionally? It won't be great for performance if you're reindexing records when you're not testing search.

**Comment by elskwid** [comment]
@tilsammans & @ankane,

I've had some success using FactoryGirl a `trait` for this so that it's only done when needed/requested.

```ruby
# factory
FactoryGirl.define do
  factory :product do
    # ...

    # Note: This should be the last trait in the list so `reindex` is called
    # after all the other callbacks complete.
    trait :reindex do
      after(:create) do |product, _evaluator|
        product.reindex(refresh: true)
      end
    end
  end
end

# use it
FactoryGirl.create(:product, :some_trait, :reindex, some_attribute: "foo")
```

**Comment by ankane** [comment]
Hey @elskwid, that sounds like a great approach.

**Comment by tilsammans** [comment]
That seems like a good approach! I'll amend the PR and rebase.

I've had really no performance issues btw, but this seems cleaner.

**Comment by tilsammans** [comment]
@ankane all done! thanks @elskwid

**Comment by ankane** [comment]
Great, thank you both 💯

**Comment by elskwid** [comment]
👍  Glad I could help. Thanks for the PR @tilsammans and thanks for the project @ankane. Take care!

**Pull request merged**
