### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bdelmas**
See https://github.com/ankane/searchkick/issues/563

### CODE REVIEW

**Comment by ankane** [comment]
Thanks Benjamin. The wording sounds a bit odd to me. How about:

If you use a custom mapping, you'll need to use custom searching as well.

**Comment by ankane** [comment]
Thanks @bdelmas

**Comment by bdelmas** [comment]
Hi Andrew! No problem. Just trying to help where I can. :)

**Comment by ankane** [comment]
A number of people have asked about this before, so I'm sure this will help future readers.

**Pull request merged**
